name: backend

services:
  auth:
    image: cosmtrek/air
    # working_dir value has to be the same of mapped volume
    working_dir: /auth
    ports:
      - 8080:8080
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./auth/:/auth/